#!/bin/bash

function IsNext()
{
    if [[ $(basename $PWD) == *Site* ]] && [[ ! $(basename $PWD) == *Api* ]]; then
        return 0;
    fi
    if [[ $(basename $PWD) == *Next* ]]; then
        return 0;
    fi
    if [ -d pages ]; then
        return 0;
    fi
    return 1;
}
